# Edit this file everytime you commit an update and if you want it to redeploy on Portainer Try 3
<<<<<<< HEAD
version: "3"
=======
version: "3.0.1"
>>>>>>> 6f9fc20 (commit 5)

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3200:3200
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
